#!/usr/bin/env ruby

require 'active_support/json'
require 'net/https'
require 'yaml'
require 'faker'
hostname = "dev.dcloud.org"
http = Net::HTTP.new(hostname, 443)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

(0..20).each do | pass |
  request = Net::HTTP::Get.new( '/api/upload' )
  auth = YAML::load(File.read('dev_credentials.yml'))
  request.basic_auth( auth[:login], auth[:password] )
  request.set_form_data( {:file=>'http://lorum.dev/file.pdf', :title=>Faker::Lorem.sentence } )

  resp = http.request( request )
  data = ActiveSupport::JSON.decode( resp.body )
  puts data['id']
  
end
